import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { toIdentifier, toSafeDirName, toTypeName, uniqueNames } from "./names.ts";
import { schemaToType } from "./schema-to-ts.ts";
import type { CompileWarning, IntrospectedMcp } from "./types.ts";

export function generateSkillPackage(params: {
  mcps: IntrospectedMcp[];
  outDir: string;
  skillName: string;
  warnings: CompileWarning[];
}): string {
  const skillDir = join(params.outDir, params.skillName);
  mkdirSync(join(skillDir, "scripts", "runtime"), { recursive: true });
  mkdirSync(join(skillDir, "scripts", "generated"), { recursive: true });

  writeFileSync(join(skillDir, "SKILL.md"), skillMarkdown(params.skillName, params.mcps), "utf8");
  writeFileSync(join(skillDir, "package.json"), JSON.stringify({ type: "module" }, null, 2), "utf8");
  writeFileSync(join(skillDir, "scripts", "runtime", "mcp-adapter.ts"), runtimeAdapterSource(), "utf8");
  writeFileSync(join(skillDir, "scripts", "runtime", "manifest.json"), JSON.stringify(manifest(params.mcps), null, 2), "utf8");

  for (const mcp of params.mcps) {
    const mcpDirName = toSafeDirName(mcp.server.id);
    const dir = join(skillDir, "scripts", "generated", mcpDirName);
    mkdirSync(dir, { recursive: true });
    const functionNames = uniqueNames(mcp.tools.map((tool) => tool.name));
    writeFileSync(join(dir, "types.ts"), typesSource(mcp, functionNames), "utf8");
    writeFileSync(join(dir, "functions.ts"), functionsSource(mcp, functionNames), "utf8");
  }

  return skillDir;
}

function skillMarkdown(skillName: string, mcps: IntrospectedMcp[]): string {
  const serverList = mcps
    .map((mcp) => `- ${mcp.server.id}: ${mcp.tools.length} generated tool function${mcp.tools.length === 1 ? "" : "s"}`)
    .join("\n");
  return `---\nname: ${skillName}\ndescription: Use generated TypeScript wrappers for configured MCP servers. Trigger this skill when a task should call MCP tools as typed code instead of ad hoc tool invocations.\n---\n\n# ${skillName}\n\nUse the generated TypeScript modules in \`scripts/generated/<mcp-id>/functions.ts\` to call MCP tools through typed async functions.\n\nGenerated MCPs:\n${serverList || "- No MCP tools were generated."}\n\nThe runtime adapter reads \`scripts/runtime/manifest.json\` and connects to the compiled MCP server definitions. OAuth credential reuse is not implemented in this version; stdio servers and HTTP servers with bearer/static/env headers are supported.\n`;
}

function manifest(mcps: IntrospectedMcp[]): unknown {
  return {
    generatedAt: new Date().toISOString(),
    servers: mcps.map((mcp) => ({
      id: mcp.server.id,
      command: mcp.server.command,
      args: mcp.server.args,
      cwd: mcp.server.cwd,
      env: mcp.server.env,
      env_vars: mcp.server.env_vars,
      url: mcp.server.url,
      bearer_token_env_var: mcp.server.bearer_token_env_var,
      http_headers: mcp.server.http_headers,
      env_http_headers: mcp.server.env_http_headers,
      tool_timeout_sec: mcp.server.tool_timeout_sec,
      tools: mcp.tools.map((tool) => tool.name)
    }))
  };
}

function typesSource(mcp: IntrospectedMcp, names: Map<string, string>): string {
  const chunks = [
    `// Generated by mcp2code. Do not edit by hand.\n`,
    `export type ServerId = ${JSON.stringify(mcp.server.id)};\n`
  ];
  for (const tool of mcp.tools) {
    const functionName = names.get(tool.name) ?? toIdentifier(tool.name, "tool");
    const typeBase = toTypeName(functionName);
    chunks.push(`export type ${typeBase}Input = ${schemaToType(tool.inputSchema, "Record<string, unknown>")};\n`);
    chunks.push(`export type ${typeBase}Output = ${schemaToType(tool.outputSchema, "unknown")};\n`);
  }
  return chunks.join("\n");
}

function functionsSource(mcp: IntrospectedMcp, names: Map<string, string>): string {
  const imports = [`import { callTool, type CallOptions } from "../../runtime/mcp-adapter.ts";`];
  const typeImports = mcp.tools.flatMap((tool) => {
    const functionName = names.get(tool.name) ?? toIdentifier(tool.name, "tool");
    const typeBase = toTypeName(functionName);
    return [`${typeBase}Input`, `${typeBase}Output`];
  });
  imports.push(`import type { ${typeImports.join(", ")} } from "./types.ts";`);

  const functions = mcp.tools.map((tool) => {
    const functionName = names.get(tool.name) ?? toIdentifier(tool.name, "tool");
    const typeBase = toTypeName(functionName);
    const comment = tool.description ? `/** ${tool.description.replace(/\*\//g, "* /")} */\n` : "";
    return `${comment}export async function ${functionName}(args: ${typeBase}Input, options?: CallOptions): Promise<${typeBase}Output> {\n  return callTool<${typeBase}Output>(${JSON.stringify(mcp.server.id)}, ${JSON.stringify(tool.name)}, args, options);\n}\n`;
  });

  return `// Generated by mcp2code. Do not edit by hand.\n${imports.join("\n")}\n\n${functions.join("\n")}`;
}

function runtimeAdapterSource(): string {
  return `// Generated by mcp2code. Shared runtime for compiled MCP wrappers.\nimport { spawn } from "node:child_process";\nimport { readFileSync } from "node:fs";\nimport { dirname, join } from "node:path";\nimport { fileURLToPath } from "node:url";\nimport { createInterface } from "node:readline";\n\nexport type CallOptions = {\n  timeoutMs?: number;\n  env?: Record<string, string>;\n};\n\ntype ServerConfig = {\n  id: string;\n  command?: string;\n  args?: string[];\n  cwd?: string;\n  env?: Record<string, string>;\n  env_vars?: Array<string | { name: string; source?: "local" | "remote" }>;\n  url?: string;\n  bearer_token_env_var?: string;\n  http_headers?: Record<string, string>;\n  env_http_headers?: Record<string, string>;\n  tool_timeout_sec?: number;\n};\n\ntype Manifest = { servers: ServerConfig[] };\n\ntype JsonRpcResponse = {\n  id?: number;\n  result?: unknown;\n  error?: { code: number; message: string; data?: unknown };\n};\n\nconst runtimeDir = dirname(fileURLToPath(import.meta.url));\nconst manifest = JSON.parse(readFileSync(join(runtimeDir, "manifest.json"), "utf8")) as Manifest;\n\nexport async function callTool<T>(serverId: string, toolName: string, args: unknown, options: CallOptions = {}): Promise<T> {\n  const server = manifest.servers.find((item) => item.id === serverId);\n  if (!server) throw new Error(\`Unknown MCP server: \${serverId}\`);\n  const timeoutMs = options.timeoutMs ?? (server.tool_timeout_sec ?? 60) * 1000;\n  const result = server.command\n    ? await callStdio(server, toolName, args, timeoutMs, options.env)\n    : await callHttp(server, toolName, args, timeoutMs, options.env);\n  if (result && typeof result === "object" && "structuredContent" in result) return (result as { structuredContent: T }).structuredContent;\n  return result as T;\n}\n\nasync function callStdio(server: ServerConfig, toolName: string, args: unknown, timeoutMs: number, envOverride?: Record<string, string>): Promise<unknown> {\n  const childEnv = { ...process.env, ...server.env, ...envOverride };\n  for (const forwarded of server.env_vars ?? []) {\n    const name = typeof forwarded === "string" ? forwarded : forwarded.name;\n    if (process.env[name] !== undefined) childEnv[name] = process.env[name];\n  }\n  const child = spawn(server.command!, server.args ?? [], { cwd: server.cwd, env: childEnv, stdio: ["pipe", "pipe", "pipe"] });\n  let nextId = 1;\n  const pending = new Map<number, { resolve: (value: unknown) => void; reject: (error: Error) => void }>();\n  createInterface({ input: child.stdout }).on("line", (line) => {\n    let message: JsonRpcResponse;\n    try { message = JSON.parse(line); } catch { return; }\n    if (typeof message.id !== "number") return;\n    const entry = pending.get(message.id);\n    if (!entry) return;\n    pending.delete(message.id);\n    if (message.error) entry.reject(new Error(message.error.message));\n    else entry.resolve(message.result);\n  });\n  child.once("exit", (code, signal) => {\n    const error = new Error(\`MCP server exited (\${code ?? signal})\`);\n    for (const entry of pending.values()) entry.reject(error);\n    pending.clear();\n  });\n  const request = (method: string, params: unknown) => new Promise<unknown>((resolve, reject) => {\n    const id = nextId++;\n    const timer = setTimeout(() => {\n      pending.delete(id);\n      reject(new Error(\`MCP request timed out: \${method}\`));\n    }, timeoutMs);\n    pending.set(id, {\n      resolve: (value) => { clearTimeout(timer); resolve(value); },\n      reject: (error) => { clearTimeout(timer); reject(error); }\n    });\n    child.stdin.write(JSON.stringify({ jsonrpc: "2.0", id, method, params }) + "\\n");\n  });\n  try {\n    await request("initialize", { protocolVersion: "2024-11-05", capabilities: {}, clientInfo: { name: "mcp2code-generated", version: "0.1.0" } });\n    child.stdin.write(JSON.stringify({ jsonrpc: "2.0", method: "notifications/initialized", params: {} }) + "\\n");\n    return await request("tools/call", { name: toolName, arguments: args ?? {} });\n  } finally {\n    child.kill();\n  }\n}\n\nasync function callHttp(server: ServerConfig, toolName: string, args: unknown, timeoutMs: number, envOverride?: Record<string, string>): Promise<unknown> {\n  if (!server.url) throw new Error(\`MCP server \${server.id} has no URL\`);\n  const env = { ...process.env, ...envOverride };\n  const headers: Record<string, string> = { "content-type": "application/json", accept: "application/json, text/event-stream", ...server.http_headers };\n  for (const [header, envName] of Object.entries(server.env_http_headers ?? {})) {\n    if (env[envName] !== undefined) headers[header] = env[envName]!;\n  }\n  if (server.bearer_token_env_var && env[server.bearer_token_env_var]) headers.authorization = \`Bearer \${env[server.bearer_token_env_var]}\`;\n  await httpRequest(server.url, headers, "initialize", { protocolVersion: "2024-11-05", capabilities: {}, clientInfo: { name: "mcp2code-generated", version: "0.1.0" } }, timeoutMs);\n  await httpRequest(server.url, headers, "notifications/initialized", {}, timeoutMs);\n  return httpRequest(server.url, headers, "tools/call", { name: toolName, arguments: args ?? {} }, timeoutMs);\n}\n\nasync function httpRequest(url: string, headers: Record<string, string>, method: string, params: unknown, timeoutMs: number): Promise<unknown> {\n  const controller = new AbortController();\n  const timer = setTimeout(() => controller.abort(), timeoutMs);\n  try {\n    const response = await fetch(url, { method: "POST", signal: controller.signal, headers, body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params }) });\n    if (!response.ok) throw new Error(\`HTTP MCP request failed with \${response.status}\`);\n    const message = await response.json() as JsonRpcResponse;\n    if (message.error) throw new Error(message.error.message);\n    return message.result;\n  } finally {\n    clearTimeout(timer);\n  }\n}\n`;
}
